[package]
name = "contra-guardian-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-utils = []

[dependencies]
fastcrypto.workspace = true
anyhow.workspace = true
bcs.workspace = true
serde.workspace = true
serde-big-array.workspace = true
thiserror = "2"
hpke = "0.12"
chacha20poly1305 = "0.10"
rand = "0.8"
