[package]
name = "contra-guardian-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fastcrypto.workspace = true
anyhow.workspace = true
bcs.workspace = true
serde.workspace = true
thiserror = "2"
hpke = "0.12"
rand = "0.8"

[features]
non-enclave-dev = ["testing"]
# Exposes deterministic constructors for tests.
testing = []
