[package]
name = "contra-guardian-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "11fdc522f048b08ae6073a3f06162009a33f6f1b" }
bcs = "0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
