// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Node-only deploy helpers: Move package compilation + `ContraInitializer`.
 * For browser-safe publish/object helpers see `ts-sdk/utils`.
 */

import { execSync } from 'node:child_process';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Bytecodes } from './publish.js';

// Re-export the browser-safe surface so Node callers only need one import.
export * from './index.js';

export { ContraInitializer } from './contra_initializer.js';

/**
 * Get the current chain identifier from the active Sui CLI environment.
 * Newer CLIs print decorated multi-line output (`Base58: <digest>` plus
 * extra lines) while older ones print a bare id (e.g. the 8-hex-char short
 * form); raw multi-line output written into a toml string breaks parsing,
 * so extract a single clean token either way.
 */
function getChainId(): string {
	const output = execSync('sui client chain-identifier', { encoding: 'utf-8' });
	// A full chain-id digest is 32 bytes, i.e. 43-44 base58 characters.
	const base58 = output.match(/Base58:\s*([1-9A-HJ-NP-Za-km-z]{40,50})/);
	if (base58) return base58[1];
	const bare = output.trim().split('\n')[0].trim();
	if (/^[0-9a-zA-Z]{4,64}$/.test(bare)) return bare;
	throw new Error(`unexpected 'sui client chain-identifier' output: ${output.trim()}`);
}

/**
 * `testnet` and `mainnet` are built-in Sui Move environments: the toolchain
 * already knows their chain IDs, and declaring them under `[environments]`
 * fails to build ("Cannot override default environments"). Only custom envs
 * (e.g. `devnet`, which is wiped and re-keyed) need an explicit entry.
 */
function isSystemEnv(env: string): boolean {
	return env === 'testnet' || env === 'mainnet';
}

/**
 * Ensure a Move.toml has an `[environments]` entry for `env` with the
 * current chain ID. Patches the file in place and returns a restore function.
 * `env` defaults to `devnet`; pass `testnet` (etc.) to target another network.
 */
export function patchMoveToml(packagePath: string, env = 'devnet'): () => void {
	// System envs (testnet/mainnet) are implicit; declaring them breaks the build.
	if (isSystemEnv(env)) return () => {};

	const tomlPath = join(packagePath, 'Move.toml');
	const original = readFileSync(tomlPath, 'utf-8');
	const chainId = getChainId();

	if (!original.includes('[environments]')) {
		writeFileSync(tomlPath, original + `\n[environments]\n${env} = "${chainId}"\n`);
	}

	return () => writeFileSync(tomlPath, original);
}

/**
 * Write a `[published.<env>]` entry (default `devnet`) to a Move package's
 * `Published.toml` pointing to `packageId` at the current chain ID, so
 * subsequent builds of downstream packages link to this freshly-published
 * address. Returns a restore function that puts `Published.toml` back to its
 * previous state (or removes it if it didn't exist).
 *
 * Use this right after publishing a package via `publishBytecodes` to make
 * its dependents see it as already-published, e.g.:
 *
 *     const { packageId } = await publishBytecodes(...);
 *     const restore = patchPublishedToml(contraMoveDir, packageId);
 *     try {
 *       const bytes = compileMovePackage(downstreamDir, { withUnpublishedDeps: true });
 *       await publishBytecodes(bytes, ...);
 *     } finally {
 *       restore();
 *     }
 */
export function patchPublishedToml(
	packagePath: string,
	packageId: string,
	env = 'devnet',
): () => void {
	const tomlPath = join(packagePath, 'Published.toml');
	const existed = existsSync(tomlPath);
	const original = existed ? readFileSync(tomlPath, 'utf-8') : null;
	const chainId = getChainId();

	// Only the linkage fields the resolver needs; the optional metadata a CLI
	// publish would record (toolchain-version, build-config) is omitted.
	const entry = `# Generated by contra-utils for the current build; restored after.

[published.${env}]
chain-id = "${chainId}"
published-at = "${packageId}"
original-id = "${packageId}"
version = 1
upgrade-capability = "0x0"
`;
	writeFileSync(tomlPath, entry);

	return () => {
		if (original !== null) writeFileSync(tomlPath, original);
		else if (existsSync(tomlPath)) unlinkSync(tomlPath);
	};
}

/** Compile a Move package to base64 bytecodes via `sui move build`. Builds
 *  against the `env` environment (default `devnet`). */
export function compileMovePackage(
	packagePath: string,
	options?: { withUnpublishedDeps?: boolean; env?: string },
): Bytecodes {
	const env = options?.env ?? 'devnet';
	const unpubFlag = options?.withUnpublishedDeps ? ' --with-unpublished-dependencies' : '';
	const output = execSync(
		`sui move build --dump-bytecode-as-base64 --path ${packagePath} -e ${env}${unpubFlag}`,
		{ encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
	);
	return JSON.parse(output) as Bytecodes;
}
