# Copyright (c) Mysten Labs, Inc.
# SPDX-License-Identifier: Apache-2.0

FROM rust:1.90-alpine3.22 AS build
RUN apk add --no-cache musl-dev
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY .cargo .cargo
COPY guardian guardian
RUN cargo build --locked --release -p contra-guardian-enclave

FROM alpine:3.21
RUN apk add --no-cache socat
COPY --from=build /src/target/release/contra-guardian-enclave /usr/local/bin/contra-guardian-enclave
COPY guardian/docker/run.sh /usr/local/bin/run.sh
ENTRYPOINT ["/usr/local/bin/run.sh"]
